name: Setup Commitizen
description: Setup Commitizen

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Commitzen
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -U Commitizen
