import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import icAngularItems from './docs/ic-angular/typedoc-sidebar.cjs';
import icBuildAngularItems from './docs/ic-build-angular/typedoc-sidebar.cjs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api-docs',
    },
    {
      type: 'category',
      label: 'ic-angular',
      link: { type: 'doc', id: 'ic-angular/index' },
      items: icAngularItems,
    },
    {
      type: 'category',
      label: 'ic-build-angular',
      link: { type: 'doc', id: 'ic-build-angular/index' },
      items: icBuildAngularItems,
    },
  ],
};

export default sidebars;
