import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
  apiSidebar: [
    {
      type: 'category',
      label: 'ic-angular',
      items: [{ type: 'autogenerated', dirName: 'ic-angular' }],
    },
    {
      type: 'category',
      label: 'ic-build-angular',
      items: [{ type: 'autogenerated', dirName: 'ic-build-angular' }],
    },
  ],
};

export default sidebars;
