name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-commitizen

      - name: Update Changelog
        run: cz changelog

      - name: Commit and Push Changes to Repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update changelog'
          commit_options: '--no-verify --signoff'
          file_pattern: 'CHANGELOG.md'
